const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{backround: 0},
	{ScrollTo: 0},
	{"8Direction": 0},
	{playerSprite: 0},
	{Mouse: 0},
	{Bullet: 0},
	{bullet: 0},
	{Keyboard: 0},
	{Pathfinding: 0},
	{Solid: 0},
	{enemySprite: 0},
	{scoreText: 0},
	{wallSprite: 0},
	{bulletsText: 0},
	{bombSprite: 0},
	{alertTextbox: 0},
	{Text: 0},
	{rangedEnemySprite: 0},
	{rangedEnemySpriteBullet: 0},
	{infinitePoints: 0},
	{Audio: 0},
	{Sprite: 0},
	{play: 0},
	{score: 0},
	{bullets: 0},
	{areYouInvincible: 0}
];

self.InstanceType = {
	backround: class extends self.ITiledBackgroundInstance {},
	playerSprite: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	bullet: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	enemySprite: class extends self.ISpriteInstance {},
	scoreText: class extends self.ITextInstance {},
	wallSprite: class extends self.ISpriteInstance {},
	bulletsText: class extends self.ITextInstance {},
	bombSprite: class extends self.ISpriteInstance {},
	alertTextbox: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	rangedEnemySprite: class extends self.ISpriteInstance {},
	rangedEnemySpriteBullet: class extends self.ISpriteInstance {},
	infinitePoints: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	play: class extends self.ITextInstance {}
}